# makefile generated by create_makefile
# 2019. febr. 6., szerda, 16:13:34 CET

NAME = test_mnist1
OBJ= $(NAME).o 

test_mnist: $(OBJ)
	g++ -std=c++17 -O3 -o $(NAME) -L/home/jakovac/Cpp/lib $(OBJ) -lsfml-graphics -lsfml-window -lsfml-system

test_mnist.o: $(NAME).cc Mnist_db.h Structure.h Shape.h \
 Error.h Rnd.h
	g++ -std=c++17 -O3 -c -I/home/jakovac/Cpp/include $(NAME).cc

.PHONY:	clean
clean:
	clean .
